@startuml NotificationProxy+diagram.invalidOrMissingRequestBody
skinparam responseMessageBelowArrow true

title
NotificationProxy+test.invalidOrMissingRequestBody
end title

participant "Postman\n" as Postman #Orange 
participant "Data\n" as Data
participant "Collection\n" as Collection

participant "/v1/add-controller" as addCtrl #LightBlue
participant "/v1/remove-controller" as removeCtrl #LightBlue
participant "/v1/notify-controller-attribute-value-changes" as notifyCAVC #LightBlue
participant "/v1/notify-controller-object-creations" as notifyCOC #LightBlue
participant "/v1/notify-controller-object-deletions" as notifyCOD #LightBlue
participant "/v1/notify-device-alarms" as notifyAlarm #LightBlue
participant "/v1/notify-device-attribute-value-changes" as notifyDAVC #LightBlue
participant "/v1/notify-device-object-creations" as notifyDOC #LightBlue
participant "/v1/notify-device-object-deletions" as notifyDOD #LightBlue


group Preparation
  Data --\\o Postman : {servers, collectionInput}
  activate Postman
  Postman --\\o Collection : {servers, collectionInput}
end

group /v1/add-controller
  Collection --\\o Postman: {servers}
  Postman -> addCtrl: {1. missing requestBody \n2. invalid requestBody}
  addCtrl <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/remove-controller
  Collection --\\o Postman: {servers}
  Postman -> removeCtrl: {1. missing requestBody \n2. invalid requestBody}
  removeCtrl <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-controller-attribute-value-changes
  Collection --\\o Postman: {servers}
  Postman -> notifyCAVC: {1. missing requestBody \n2. invalid requestBody}
  notifyCAVC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-controller-object-creations
  Collection --\\o Postman: {servers}
  Postman -> notifyCOC: {1. missing requestBody \n2. invalid requestBody}
  notifyCOC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-controller-object-deletions
  Collection --\\o Postman: {servers}
  Postman -> notifyCOD: {1. missing requestBody \n2. invalid requestBody}
  notifyCOD <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-device-alarms
  Collection --\\o Postman: {servers}
  Postman -> notifyAlarm: {1. missing requestBody \n2. invalid requestBody}
  notifyAlarm <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-device-attribute-value-changes
  Collection --\\o Postman: {servers}
  Postman -> notifyDAVC: {1. missing requestBody \n2. invalid requestBody}
  notifyDAVC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-device-object-creations
  Collection --\\o Postman: {servers}
  Postman -> notifyDOC: {1. missing requestBody \n2. invalid requestBody}
  notifyDOC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

group /v1/notify-device-object-deletions
  Collection --\\o Postman: {servers}
  Postman -> notifyDOD: {1. missing requestBody \n2. invalid requestBody}
  notifyDOD <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 400
  end note
end

deactivate Postman

@enduml