@startuml NotificationProxy+diagram.completeness
skinparam responseMessageBelowArrow true

title
NotificationProxy+test.completeness
end title

participant "Postman\n" as Postman #Orange 
participant "Data\n" as Data
participant "Collection\n" as Collection

participant "/v1/add-controller" as addCtrl #LightBlue
participant "/v1/listen-to-controllers" as listenCtrl #LightBlue
participant "/v1/remove-controller" as removeCtrl #LightBlue
participant "/v1/notify-controller-attribute-value-changes" as notifyCAVC #LightBlue
participant "/v1/notify-controller-object-creations" as notifyCOC #LightBlue
participant "/v1/notify-controller-object-deletions" as notifyCOD #LightBlue
participant "/v1/notify-device-alarms" as notifyAlarm #LightBlue
participant "/v1/notify-device-attribute-value-changes" as notifyDAVC #LightBlue
participant "/v1/notify-device-object-creations" as notifyDOC #LightBlue
participant "/v1/notify-device-object-deletions" as notifyDOD #LightBlue


group Preparation
  Data --\\o Postman : {servers, collectionInput}
  activate Postman
  Postman --\\o Collection : {servers, collectionInput}
end

group /v1/add-controller
  Collection --\\o Postman: {servers}
  Postman -> addCtrl: {dummyControllerInfo}
  addCtrl <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/listen-to-controllers
  Collection --\\o Postman: {servers}
  Postman -> listenCtrl
  listenCtrl <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/remove-controller
  Collection --\\o Postman: {servers}
  Postman -> removeCtrl: {dummyControllerInfo}
  removeCtrl <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-controller-attribute-value-changes
  Collection --\\o Postman: {servers}
  Postman -> notifyCAVC: {dummySubscriberInfo}
  notifyCAVC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-controller-object-creations
  Collection --\\o Postman: {servers}
  Postman -> notifyCOC: {dummySubscriberInfo}
  notifyCOC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-controller-object-deletions
  Collection --\\o Postman: {servers}
  Postman -> notifyCOD: {dummySubscriberInfo}
  notifyCOD <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-alarms
  Collection --\\o Postman: {servers}
  Postman -> notifyAlarm: {dummySubscriberInfo}
  notifyAlarm <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-attribute-value-changes
  Collection --\\o Postman: {servers}
  Postman -> notifyDAVC: {dummySubscriberInfo}
  notifyDAVC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-object-creations
  Collection --\\o Postman: {servers}
  Postman -> notifyDOC: {dummySubscriberInfo}
  notifyDOC <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-object-deletions
  Collection --\\o Postman: {servers}
  Postman -> notifyDOD: {dummySubscriberInfo}
  notifyDOD <-- Postman: ResponseCode
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

deactivate Postman

@enduml