@startuml NotificationProxy+diagram.completeness
skinparam responseMessageBelowArrow true

title
NotificationProxy+test.completeness
end title

participant "Postman\n" as Postman #Orange 
participant "Data\n" as Data
participant "Collection\n" as Collection

participant "/v1/add-controller" as addCtrl #LightBlue
participant "/v1/listen-to-controllers" as listenCtrl #LightBlue
participant "/v1/remove-controller" as RemoveCtrl #LightBlue
participant "/v1/notify-controller-attribute-value-changes" as notifyCAVC #LightBlue
participant "/v1/notify-controller-object-creations" as notifyCOC #LightBlue
participant "/v1/notify-controller-object-deletions" as notifyCOD #LightBlue
participant "/v1/notify-device-alarms" as notifyAlarm #LightBlue
participant "/v1/notify-device-attribute-value-changes" as notifyDAVC #LightBlue
participant "/v1/notify-device-object-creations" as notifyDOC #LightBlue
participant "/v1/notify-device-object-deletions" as notifyDOD #LightBlue


TODO: die parameter anpassen (s. requestBodies!)

group Preparation
  Data --\\o Postman : {servers, mount-name}
  activate Postman
  Postman --\\o Collection : {servers, mount-name}
end

group /v1/add-controller
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/listen-to-controllers
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/remove-controller
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-controller-attribute-value-changes
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-controller-object-creations
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-controller-object-deletions
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-alarms
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-attribute-value-changes
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-object-creations
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

group /v1/notify-device-object-deletions
  Collection --\\o Postman: {servers}
  Postman -> foo: {mount-name}
  foo <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

deactivate Postman

@enduml