@startuml is011_NotifyingOfChangedControllerAttributeValue
skinparam responseMessageBelowArrow true

title SubscriptionCausesNotifyingOfChangedControllerAttributeValue

participant "e.g. MWDI" as Subscriber
participant "NP://v1/notify-controller-attribute-value-changes" as NP_notifyChanges
participant "ODLn://rests/notif/data-change-event-subscription/network-topology:network-topology/\ndatastore=CONFIGURATION/scope=SUBTREE/JSON" as Configuration
participant "ODLn://rests/notif/data-change-event-subscription/network-topology:network-topology/\ndatastore=OPERATIONAL/scope=SUBTREE/JSON" as Operational

Subscriber -> NP_notifyChanges: {ownIP, ownPort, ownReceiveOperation}
activate NP_notifyChanges

Configuration --> NP_notifyChanges: {notifications}
Operational --> NP_notifyChanges: {notifications}

note over NP_notifyChanges
IF operation == "updated"
end note

Subscriber <- NP_notifyChanges

deactivate NP_notifyChanges

@enduml
