@startuml is023_NotifyingOfDeviceObjectDeletion
skinparam responseMessageBelowArrow true

title SubscriptionCausesNotifyingOfDeviceObjectDeletion

participant "e.g. MWDI" as Subscriber
participant "NP://v1/notify-device-object-deletions" as NP_notifyObjectDeletion
participant "unklar: \nODLn:/rests/notif?notificationType=device}" as Device

Subscriber -> NP_notifyObjectDeletion: {ownIP, ownPort, ownReceiveOperation}
activate NP_notifyObjectDeletion

Device --> NP_notifyObjectDeletion: {notifications}

note over NP_notifyObjectDeletion
Repetitions are suppressed
end note

note over NP_notifyObjectDeletion
IF ObjectDeletionNotification: *:object-deletion-notification
counter = counter
timestamp = timestamp (not event-time)
_objectIdRef = object-id-ref (mount-name+uuid)
end note

Subscriber <- NP_notifyObjectDeletion: {MountName, counter, timestamp, logicalTerminationPointUuid, attributeName, newValue}

deactivate NP_notifyObjectDeletion

@enduml
